export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAIL = "GET_STUDENT_FAIL";

export const GET_TEACHER_REQUEST = "GET_TEACHER_REQUEST";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const GET_TEACHER_FAIL = "GET_TEACHER_FAIL";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOAD_TEACHER_REQUEST = "LOAD_TEACHER_REQUEST";
export const LOAD_TEACHER_SUCCESS = "LOAD_TEACHER_SUCCESS";
export const LOAD_TEACHER_FAIL = "LOAD_TEACHER_FAIL";

export const LOAD_STUDENT_REQUEST = "LOAD_STUDENT_REQUEST";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const LOAD_STUDENT_FAIL = "LOAD_STUDENT_FAIL";

export const FORGOTPASSWORD_REQUEST = "FORGOTPASSWORD_REQUEST";
export const FORGOTPASSWORD_SUCCESS = "FORGOTPASSWORD_SUCCESS";
export const FORGOTPASSWORD_FAIL = "FORGOTPASSWORD_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";

export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAIL = "GOOGLE_LOGIN_FAIL";

export const STUDENT_LOADED = "STUDENT_LOADED";
export const STUDENT_LOADING = "STUDENT_LOADING";

export const GET_ASSIGNMENT_REQUEST = "GET_ASSIGNMENT_REQUEST";
export const GET_ASSIGNMENT_SUCCESS = "GET_ASSIGNMENT_SUCCESS";
export const GET_ASSIGNMENT_FAIL = "GET_ASSIGNMENT_FAIL";

export const LOAD_ASSIGNMENT_REQUEST = "LOAD_ASSIGNMENT_REQUEST";
export const LOAD_ASSIGNMENT_SUCCESS = "LOAD_ASSIGNMENT_SUCCESS";
export const LOAD_ASSIGNMENT_FAIL = "LOAD_ASSIGNMENT_FAIL";

export const GET_SECTION_REQUEST = "GET_SECTION_REQUEST";
export const GET_SECTION_SUCCESS = "GET_SECTION_SUCCESS";
export const GET_SECTION_FAIL = "GET_SECTION_FAIL";

export const GET_WORK_REQUEST = "GET_WORK_REQUEST";
export const GET_WORK_SUCCESS = "GET_WORK_SUCCESS";
export const GET_WORK_FAIL = "GET_WORK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
